Resources:
  CustomVPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: "10.0.0.0/16"

  SubnetPublic:
    Type: 'AWS::EC2::Subnet'
    Properties:
      CidrBlock: "10.0.1.0/24"
      VpcId: !Ref CustomVPC

  SubnetPrivate:
    Type: 'AWS::EC2::Subnet'
    Properties:
      CidrBlock: "10.0.2.0/24"
      VpcId: !Ref CustomVPC

  
